name: test
on:
  push:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r25b
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Make Java
      run: ./gradlew :zygisk:assembleRelease
